### PR TITLE
Chapter Four Revision

### PR DESCRIPTION
**Pull request by XienManzal**
Completed issued revision on Chapter Four

### CODE REVIEW

**Comment by apquinit** [comment]
Hello @Tephaany ,

Please review Xien's PR.
You can click on "Files changed" tab to review specific updates.
Then click, Review changes button to Approve, reject or Request revision and add Review Summary.

Thanks!

**Comment by apquinit** [comment]
Hello @Tephaany , any progress on the review?

**Comment by Tephaany** [comment]
Already reviewed the revision. 

There's still something that needs to be changed with the document. The word 'Chapter', should all be in uppercase but I'll be the one to do the changes so I can merge it right away. Thanks!

**Comment by apquinit** [comment]
In that case, you can just checkout xien's branch, perform the change, push and then merge.

**Comment by apquinit** [comment]
Don't  forget that before merging, you must approve first the PR, go to Files Change Tab >>  Review Changes Button >> Approve. Once approvedm you can perform the merge.

**Comment by Tephaany** [comment]
Changes are still to be made with this Chapter, given that the system is not yet done because there are parts of the documentation that should be base on how the system will work. As of now, this will be our Chapter four, until we can update it due to the system's availability for testing.

**Pull request merged**
